Repository ruchikakengal/WebDevIn100_Days, pull requests merged in 2025-07, with the labels that each got.

#89 issue #38 Add Random quote generator
  Day-XX_QuoteGenerator/README.md
  Day-XX_QuoteGenerator/index.html
  index.js
Labels: SSOC S4, BEGINNER, points-assignment-done

#170 Added Coin Flip game
  .vscode/settings.json
  index.js
  public/Coin_Flip/6d5938dd7b271e9ad1112ac481c2c4d9.jpg
  public/Coin_Flip/coin.css
  public/Coin_Flip/coin.js
  public/Coin_Flip/index.html
Labels: SSOC S4, INTERMEDIATE, points-assignment-done

#213 fix-issue-184
  Day-1-TodoList/README.md
  Day-1-TodoList/index.html
Labels: SSOC S4, BEGINNER, points-assignment-done

#211 E- Waste Management Hub
  index.js
  public/E-WasteManagementHub/index.html
  public/E-WasteManagementHub/locations.css
  public/E-WasteManagementHub/locations.html
  public/E-WasteManagementHub/locations.js
  public/E-WasteManagementHub/script.js
  public/E-WasteManagementHub/style.css
Labels: SSOC S4, BEGINNER

#219 Project on Dice Roll SImulatorAdd files via upload
  DICE ROLL SIMULATOR/index.html
  DICE ROLL SIMULATOR/script.js
  DICE ROLL SIMULATOR/style.css
  index.js
  public/DICE ROLL SIMULATOR/index.html
  public/DICE ROLL SIMULATOR/script.js
  public/DICE ROLL SIMULATOR/style.css
Labels: SSOC S4, BEGINNER, points-assignment-done

#220 Add countdown banner (Fixes #195)
  index.js
Labels: SSOC S4, BEGINNER, points-assignment-done

#201 Issue #64 solved: URL Shortener
  index.js
Labels: SSOC S4, BEGINNER, points-assignment-done

#207 Guess My Number Game✅
  index.js
  public/Guess_My_Number/index.html
  public/Guess_My_Number/script.js
  public/Guess_My_Number/style.css
Labels: SSOC S4, BEGINNER, points-assignment-done

#223 Enhance Footer Text Visibility
  index.html
Labels: SSOC S4, BEGINNER, points-assignment-done

#224 Candycrushgame
  index.js
  public/candycrush/candy_crush.html
  public/candycrush/script.js
  public/candycrush/styles.css
Labels: SSOC S4, INTERMEDIATE, points-assignment-done

#202 Issue #63 Solution: WaterMedic
  index.js
Labels: SSOC S4, INTERMEDIATE, points-assignment-done

#263 Adding Stopwatch Project
  index.js
  public/Stopwatch/index.html
  public/Stopwatch/script.js
  public/Stopwatch/styles.css
Labels: points-assignment-done, GSSOC'25, Level 1

#255 Added New Feature Task Analysis Table
  Day-1-TodoList/README.md
  Day-1-TodoList/index.html
Labels: points-assignment-done, GSSOC'25, Level 1

#242 Resolved Issue #240: updated index.js
  index.js
Labels: SSOC S4, BEGINNER

#287 ✨ Added Dark/Light mode toggle and Navbar to Weather App
  public/Day-11_WeatherApp/index.html
  public/Day-11_WeatherApp/script.js
  public/Day-11_WeatherApp/style.css
Labels: points-assignment-done, GSSOC'25, Level 1

#288 [UPDATED! - Fork] QR generator
  index.js
  public/Day-22_QRCodeGenerator/index.html
  public/Day-22_QRCodeGenerator/script.js
  public/Day-22_QRCodeGenerator/style.css
Labels: SSoC25, BEGINNER, points-assignment-done

#304 Added Day-23_Target_Reflex_Test (Fixes #251)
  index.js
  public/Day-23_QRCodeGenerator/index.html
  public/Day-23_QRCodeGenerator/script.js
  public/Day-23_QRCodeGenerator/style.css
  public/Day-28_Target_Reflex_Test/index.html
  public/Day-28_Target_Reflex_Test/script.js
  public/Day-28_Target_Reflex_Test/styles.css
Labels: GSSOC'25, Level 2

#324 Added GiggleBits - Programming Joke Generator Web App
  index.js
  public/GiggleBits/index.html
  public/Snake-and-Ladder-Game/dice-rolling.mp3
  public/Snake-and-Ladder-Game/index.html
  public/Snake-and-Ladder-Game/script.js
  public/Snake-and-Ladder-Game/snake ladder.png
  public/Snake-and-Ladder-Game/style.css
  public/Snake-and-Ladder-Game/win-sound.mp3
Labels: GSSOC'25, Level 1

#341 Note Taker
  index.js
  public/Day-42_NoteTaker/index.html
  public/Day-42_NoteTaker/script.js
  public/Day-42_NoteTaker/style.css
Labels: GSSOC'25, Level 2

#315 contributors page added
  contributors.html
  index.html
  index.js
  public/background.jpg
Labels: GSSOC'25, Level 1

#332 Day31 - Move the project in public folder, resolved merge conflicts.
  index.js
  public/Etch-a-Sketch/index.html
  public/Etch-a-Sketch/script.js
  public/Etch-a-Sketch/style.css
Labels: GSSOC'25, Level 1

#371 Add Real-Time World Clock with Smooth UI and Responsive
  index.js
  public/World_Clock/images/logo.svg
  public/World_Clock/index.html
  public/World_Clock/local.js
  public/World_Clock/script.js
  public/World_Clock/style.css
Labels: GSSOC'25, Level 1

#357 added wordle inspired word guess game
  index.js
  public/E-Commerce UI/README.md
  public/E-Commerce UI/index.html
  public/Wordle_Based_Game/README.md
  public/Wordle_Based_Game/index.html
  public/Wordle_Based_Game/script.js
  public/Wordle_Based_Game/style.css
Labels: SSoC25, Intermediate

#367 Added Gradient Generator
  index.js
  public/Gradient_Generator/index.html
  public/Gradient_Generator/script.js
  public/Gradient_Generator/style.css
Labels: SSoC25, Beginner

#399 Added Space Jumper - Flying Game
  index.js
  public/Space-Jumper-Game/index.html
Labels: GSSoC'25, Level 2

#420 added E-commerce UI and wordle based game
  index.js
  public/Day52_E-Commerce_UI/index.html
  public/Day52_E-Commerce_UI/style.css
  public/Day53-Word-Guess-Game/index.html
  public/Day53-Word-Guess-Game/script.js
  public/Day53-Word-Guess-Game/style.css
Labels: SSoC25, Beginner, Intermediate

#386 Add Day-43: 4 in a Row
  index.js
  public/Day-57_4_in_a_row/index.html
  public/Day-57_4_in_a_row/script.js
  public/Day-57_4_in_a_row/style.css
Labels: GSSoC'25, Level 2

#422 memory game app
  index.js
  public/Memory Game App/README.md
  public/Memory Game App/index.html
  public/Memory Game App/script.js
  public/Memory Game App/style.css
Labels: SSoC25, Intermediate

#433 Added Budget Tracker Web App
  index.js
  public/Budget-Tracker/index.html
Labels: GSSoC'25, Level 2
