Repository ruchikakengal/WebDevIn100_Days, pull requests merged in 2025-08, with the labels that each got.

#448 Day 75: MyPaint Project
  index.js
  public/day75-mypaint/index.html
Labels: SSoC25, Beginner

#421 🚀 Complete UI Modernization: Table-Only Gallery + About Challenge Section
  contributors.html
  index.html
  scripts/app.js
  scripts/modern-app.js
  styles/footer.css
  styles/header.css
  styles/main.css
  styles/modern-theme.css
  styles/navbar.css
  styles/navigation.css
  styles/project-cards.css
  styles/projects.css
Labels: GSSoC'25, Level 2

#441 Game update
  public/Space-War-Game/audio.js
  public/Space-War-Game/game.js
  public/Space-War-Game/index.html
  public/Space-War-Game/style.css
Labels: SSoC25, Beginner

#461 Created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: GSSoC'25, Level 1

#502 add my project
  public/University_managment_system/WhatsApp Image 2024-09-27 at 21.01.37_9eca541b.jpg
  public/University_managment_system/about-img.png
  public/University_managment_system/dashboard.css
  public/University_managment_system/dashboard.js
  public/University_managment_system/dashbord.html
  public/University_managment_system/demo main.html
  public/University_managment_system/image copy.png
  public/University_managment_system/image.png
  public/University_managment_system/index.html
  public/University_managment_system/login.css
  public/University_managment_system/login.html
  public/University_managment_system/script.js
  public/University_managment_system/style.css
  scripts/app.js
Labels: GSSoC'25, Level 2

#536 Issue 342
  public/QuizProgram/index.html
  public/QuizProgram/script.js
  public/QuizProgram/style.css
  scripts/app.js
Labels: GSSoC'25, Level 1

#538 Added Pixel art maker
  public/Day-76_PixelArt/index.html
  public/Day-76_PixelArt/styles.css
  scripts/app.js
Labels: GSSoC'25, Level 2

#528 Game+
  public/Day-70/assets/couple.svg
  public/Day-70/assets/heart.svg
  public/Day-70/fav.svg
  public/Day-70/index.html
  public/Day-70/js/audio.js
  public/Day-70/js/cardMaker.js
  public/Day-70/js/compatibility.js
  public/Day-70/js/confession.js
  public/Day-70/js/dateSpinner.js
  public/Day-70/js/main.js
  public/Day-70/js/memoryGame.js
  public/Day-70/styles/animations.css
  public/Day-70/styles/main.css
  scripts/app.js
Labels: SSoC25, Beginner

#562 Helicopter Game+
  public/Day-55/fav.svg
  public/Day-55/game.js
  public/Day-55/index.html
  public/Day-55/style.css
Labels: SSoC25, Intermediate

#576 Readme update
  README.md
Labels: SSoC25, Beginner, GSSoC'25, Level 1

#563 Robo Game+
  public/Day-72/fav.svg
  public/Day-72/index.html
  public/Day-72/script.js
  public/Day-72/styles.css
Labels: SSoC25, Intermediate

#580 Roast Game+
  public/Day-92/index.html
  public/Day-92/roast-templates.js
  public/Day-92/script.js
  public/Day-92/styles.css
Labels: SSoC25, Beginner

#590 Mystry Game+
  public/Day-96/index.html
  public/Day-96/script.js
  public/Day-96/styles.css
Labels: SSoC25, Beginner

#523 flappy-bird game added
  public/flappy-bird/img/BG.png
  public/flappy-bird/img/bird/b0.png
  public/flappy-bird/img/bird/b1.png
  public/flappy-bird/img/bird/b2.png
  public/flappy-bird/img/botpipe.png
  public/flappy-bird/img/getready.png
  public/flappy-bird/img/go.png
  public/flappy-bird/img/ground.png
  public/flappy-bird/img/ground/g0.png
  public/flappy-bird/img/ground/g1.png
  public/flappy-bird/img/tap/t0.png
  public/flappy-bird/img/tap/t1.png
  public/flappy-bird/img/toppipe.png
  public/flappy-bird/index.html
  public/flappy-bird/script.js
  public/flappy-bird/sfx/die.wav
  public/flappy-bird/sfx/flap.wav
  public/flappy-bird/sfx/hit.wav
  public/flappy-bird/sfx/score.wav
  public/flappy-bird/sfx/start.wav
  public/flappy-bird/styles.css
  scripts/app.js
Labels: SSoC25, Intermediate, GSSoC'25, Level 1

#601 Fix: auto-scroll on pagination
  scripts/app.js
Labels: GSSoC'25, Level 1

#612 RouleteSpin Game+
  public/Day-98/assets/css/styles.css
  public/Day-98/assets/js/scripts.js
  public/Day-98/assets/js/utils.js
  public/Day-98/index.html
Labels: SSoC25, Beginner

#613 Puzzle Game+
  public/Day-89/1.jpg
  public/Day-89/10.jpg
  public/Day-89/2.jpg
  public/Day-89/3.jpg
  public/Day-89/4.jpg
  public/Day-89/5.jpg
  public/Day-89/5x5 puzzle challenge/1.jpg
  public/Day-89/5x5 puzzle challenge/10.jpg
  public/Day-89/5x5 puzzle challenge/11.jpg
  public/Day-89/5x5 puzzle challenge/12.jpg
  public/Day-89/5x5 puzzle challenge/13.jpg
  public/Day-89/5x5 puzzle challenge/14.jpg
  public/Day-89/5x5 puzzle challenge/15.jpg
  public/Day-89/5x5 puzzle challenge/16.jpg
  public/Day-89/5x5 puzzle challenge/17.jpg
  public/Day-89/5x5 puzzle challenge/18.jpg
  public/Day-89/5x5 puzzle challenge/19.jpg
  public/Day-89/5x5 puzzle challenge/2.jpg
  public/Day-89/5x5 puzzle challenge/20.jpg
  public/Day-89/5x5 puzzle challenge/21.jpg
  public/Day-89/5x5 puzzle challenge/22.jpg
  public/Day-89/5x5 puzzle challenge/23.jpg
  public/Day-89/5x5 puzzle challenge/24.jpg
  public/Day-89/5x5 puzzle challenge/25.jpg
  public/Day-89/5x5 puzzle challenge/26.jpg
  public/Day-89/5x5 puzzle challenge/3.jpg
  public/Day-89/5x5 puzzle challenge/4.jpg
  public/Day-89/5x5 puzzle challenge/5.jpg
  public/Day-89/5x5 puzzle challenge/5_.jpg
  public/Day-89/5x5 puzzle challenge/6.jpg
  public/Day-89/5x5 puzzle challenge/7.jpg
  public/Day-89/5x5 puzzle challenge/8.jpg
  public/Day-89/5x5 puzzle challenge/9.jpg
  public/Day-89/6.jpg
  public/Day-89/7.jpg
  public/Day-89/8.jpg
  public/Day-89/9.jpg
  public/Day-89/fav.svg
  public/Day-89/index.html
  public/Day-89/logo.png
  public/Day-89/puzzle.css
  public/Day-89/puzzle.js
Labels: SSoC25, Beginner

#638 Add “Peaceful New Tab” Chrome Extension (GSSoC’25)
  peaceful-new-tab/background.js
  peaceful-new-tab/content.js
  peaceful-new-tab/index.html
  peaceful-new-tab/manifest.json
  peaceful-new-tab/script.js
  peaceful-new-tab/styles.css
Labels: GSSoC'25, Level 2

#630 invoice Generator project added
  public/Invoice-Builder/index.html
  public/Invoice-Builder/script.js
  public/Invoice-Builder/styles.css
  scripts/app.js
Labels: SSoC25, Intermediate, GSSoC'25, Level 2

#573 Update index.html of portfolio
  public/Day-72_Portfolio/index.html
Labels: SSoC25, Intermediate

#644 Mario Game+
  public/Day-62/css/styles.css
  public/Day-62/index.html
  public/Day-62/js/audio.js
  public/Day-62/js/collectibles.js
  public/Day-62/js/enemy.js
  public/Day-62/js/game.js
  public/Day-62/js/input.js
  public/Day-62/js/level.js
  public/Day-62/js/physics.js
  public/Day-62/js/player.js
  public/Day-62/js/ui.js
  public/Day-62/sounds/background.mp3
  public/Day-62/sounds/hit.mp3
  public/Day-62/sounds/success.mp3
Labels: SSoC25, Intermediate, points-assignment-done

#595 ADDED Memory Grid Rush #447
  public/Memory_Grid_Rush/index.html
  public/Memory_Grid_Rush/script.js
  public/Memory_Grid_Rush/style.css
  scripts/app.js
Labels: SSoC25, Intermediate, points-assignment-done

#658 Vaani : AI Assistant
  Vaani_b.svg
  Vaani_w.svg
  chatbot.css
  chatbot.js
  index.html
  styles/main.css
Labels: SSoC25, Intermediate, points-assignment-done

#618 Pong Game+
  public/Day-83/index.html
  public/Day-83/js/ai.js
  public/Day-83/js/audio.js
  public/Day-83/js/ball.js
  public/Day-83/js/controls.js
  public/Day-83/js/game.js
  public/Day-83/js/paddle.js
  public/Day-83/js/powerups.js
  public/Day-83/js/storage.js
  public/Day-83/js/ui.js
  public/Day-83/style.css
Labels: SSoC25, Beginner, points-assignment-done

#575 Project: CineSearch – A Sleek Movie Search Interface Using OMDb API ,added successfully
  contributors.html
  public/CineSearch/index.html
  public/CineSearch/movie.html
  public/CineSearch/movie.js
  public/CineSearch/script.js
  public/CineSearch/style.css
  scripts/app.js
Labels: points-assignment-done, GSSoC'25, Level 1

#677 ADDED Bubble Pop Game #676
  public/Bubble_Pop/index.html
  public/Bubble_Pop/script.js
  public/Bubble_Pop/style.css
  scripts/app.js
Labels: SSoC25, Intermediate, points-assignment-done

#747 OriginalDay Fix
  scripts/app.js
Labels: bug, SSoC25, Beginner, points-assignment-done

#769 Bug Fix
  contributors.html
Labels: bug, SSoC25, Beginner, points-assignment-done

#751 L&T+
  public/Day-152/index.html
  public/Day-152/script.js
  public/Day-152/style.css
Labels: bug, SSoC25, Beginner, points-assignment-done

#770 Survival Game+
  public/Day-155/game-engine.js
  public/Day-155/index.html
  public/Day-155/leaderboard.html
  public/Day-155/leaderboard.js
  public/Day-155/mini-games.js
  public/Day-155/script.js
  public/Day-155/styles.css
Labels: SSoC25, Beginner, points-assignment-done

#771 Spin Game+
  public/Day-156/index.html
  public/Day-156/script.js
  public/Day-156/styles.css
Labels: SSoC25, Beginner, points-assignment-done

#774 Puzzle Game+
  public/Day-158/index.html
  public/Day-158/script.js
  public/Day-158/style.css
Labels: SSoC25, Beginner, points-assignment-done

#775 LightHouse Game+
  public/Day-159/index.html
  public/Day-159/style.css
Labels: SSoC25, Beginner, points-assignment-done

#778 Hacker+
  public/Day-162/index.html
  public/Day-162/scripts/audio.js
  public/Day-162/scripts/effects.js
  public/Day-162/scripts/filesystem.js
  public/Day-162/scripts/main.js
  public/Day-162/scripts/minigames.js
  public/Day-162/scripts/storage.js
  public/Day-162/scripts/terminal.js
  public/Day-162/styles/effects.css
  public/Day-162/styles/main.css
  public/Day-162/styles/terminal.css
Labels: SSoC25, Beginner, points-assignment-done

#779 Story+
  public/Day-163/css/animations.css
  public/Day-163/css/styles.css
  public/Day-163/css/themes.css
  public/Day-163/data/story-templates.js
  public/Day-163/data/themes.js
  public/Day-163/index.html
  public/Day-163/js/app.js
  public/Day-163/js/storage.js
  public/Day-163/js/story-data.js
  public/Day-163/js/story-generator.js
  public/Day-163/js/utils.js
  public/Day-163/scripts/app.js
  public/Day-163/scripts/audio-manager.js
  public/Day-163/scripts/background-effects.js
  public/Day-163/scripts/choice-system.js
  public/Day-163/scripts/export-manager.js
  public/Day-163/scripts/export.js
  public/Day-163/scripts/narration.js
  public/Day-163/scripts/storage-manager.js
  public/Day-163/scripts/storage.js
  public/Day-163/scripts/story-engine.js
  public/Day-163/scripts/story-generator.js
  public/Day-163/scripts/theme-manager.js
  public/Day-163/scripts/themes.js
  public/Day-163/styles/animations.css
  public/Day-163/styles/main.css
  public/Day-163/styles/themes.css
Labels: SSoC25, Intermediate, points-assignment-done

#780 Translator+
  public/Day-164/audio-engine.js
  public/Day-164/index.html
  public/Day-164/particle-background.js
  public/Day-164/script.js
  public/Day-164/styles.css
  public/Day-164/translator.js
Labels: SSoC25, Beginner, points-assignment-done

#813 Fruit Ninja Game+
  public/Fruit_Slicer_Game/index.html
  public/Fruit_Slicer_Game/script.js
  public/Fruit_Slicer_Game/styles.css
Labels: SSoC25, Beginner, points-assignment-done

#814 Cup & Ball+
  public/Day-167/index.html
  public/Day-167/script.js
  public/Day-167/style.css
Labels: SSoC25, Beginner

#816 Casino Roulette+
  public/Day-169/index.html
  public/Day-169/script.js
  public/Day-169/style.css
Labels: SSoC25, Beginner, points-assignment-done

#817 Shooting Game+
  public/Day-170/index.html
Labels: SSoC25, Beginner

#821 Signature+
  public/Day-173/index.html
  public/Day-173/script.js
  public/Day-173/style.css
Labels: SSoC25, Beginner, points-assignment-done

#822 Car Rental Website+
  public/Day-174/index.html
  public/Day-174/loo.svg
  public/Day-174/style.css
Labels: SSoC25, Beginner, points-assignment-done

#824 Treasure Hunt Game+
  public/Day-176/audio.js
  public/Day-176/index.html
  public/Day-176/particles.js
  public/Day-176/puzzles.js
  public/Day-176/script.js
  public/Day-176/styles.css
  public/Day-176/themes.js
Labels: SSoC25, Beginner, points-assignment-done

#828 Basketball Game+
  public/Day-179/index.html
  public/Day-179/script.js
  public/Day-179/style.css
Labels: SSoC25, Beginner, points-assignment-done

#829 Blocks Game+
  public/Day-180/index.html
  public/Day-180/script.js
  public/Day-180/style.css
Labels: SSoC25, Beginner, points-assignment-done

#830 Temple Run+
  public/Day-181/index.html
  public/Day-181/script.js
  public/Day-181/style.css
Labels: SSoC25, Intermediate, points-assignment-done

#831 Vaani Database Update
  chatbot.js
Labels: SSoC25, Beginner, points-assignment-done

#754 Add Email Validator
  public/Day-101_Email_Validator/about.html
  public/Day-101_Email_Validator/images/loading.svg
  public/Day-101_Email_Validator/images/logo.svg
  public/Day-101_Email_Validator/index.html
  public/Day-101_Email_Validator/script.js
  public/Day-101_Email_Validator/style.css
  scripts/app.js
Labels: points-assignment-done, GSSoC'25, Level 2

#739 Jwellery website Added
  public/Jwellery-Website/index.html
  scripts/app.js
Labels: SSoC25, Beginner, points-assignment-done, GSSoC'25, Level 1

#854 ADDED Flip Tiles Puzzle #810
  public/Flip_Tiles_Puzzle/index.html
  public/Flip_Tiles_Puzzle/script.js
  public/Flip_Tiles_Puzzle/style.css
  scripts/app.js
Labels: SSoC25, Intermediate, points-assignment-done

#865 Myntra Clone+
  public/Day-182/index.html
  public/Day-182/style.css
Labels: SSoC25, Beginner, points-assignment-done

#874 Watch Website+
  public/Day-186/assets/css/styles.css
  public/Day-186/assets/css/swiper-bundle.min.css
  public/Day-186/assets/img/favicon.png
  public/Day-186/assets/img/featured1.png
  public/Day-186/assets/img/featured2.png
  public/Day-186/assets/img/featured3.png
  public/Day-186/assets/img/home.png
  public/Day-186/assets/img/new1.png
  public/Day-186/assets/img/new2.png
  public/Day-186/assets/img/new3.png
  public/Day-186/assets/img/new4.png
  public/Day-186/assets/img/product1.png
  public/Day-186/assets/img/product2.png
  public/Day-186/assets/img/product3.png
  public/Day-186/assets/img/product4.png
  public/Day-186/assets/img/product5.png
  public/Day-186/assets/img/story.png
  public/Day-186/assets/img/testimonial.png
  public/Day-186/assets/img/testimonial1.jpg
  public/Day-186/assets/img/testimonial2.jpg
  public/Day-186/assets/img/testimonial3.jpg
  public/Day-186/assets/js/main.js
  public/Day-186/assets/js/swiper-bundle.min.js
  public/Day-186/assets/scss/base/_base.scss
  public/Day-186/assets/scss/components/_breakpoints.scss
  public/Day-186/assets/scss/components/_buttons.scss
  public/Day-186/assets/scss/components/_cart.scss
  public/Day-186/assets/scss/components/_featured.scss
  public/Day-186/assets/scss/components/_footer.scss
  public/Day-186/assets/scss/components/_header.scss
  public/Day-186/assets/scss/components/_home.scss
  public/Day-186/assets/scss/components/_new.scss
  public/Day-186/assets/scss/components/_newsletter.scss
  public/Day-186/assets/scss/components/_products.scss
  public/Day-186/assets/scss/components/_scroll.scss
  public/Day-186/assets/scss/components/_story.scss
  public/Day-186/assets/scss/components/_testimonial.scss
  public/Day-186/assets/scss/config/_variables.scss
  public/Day-186/assets/scss/layout/_layout.scss
  public/Day-186/assets/scss/styles.scss
  public/Day-186/assets/scss/theme/_theme.scss
  public/Day-186/index.html
Labels: SSoC25, Beginner, points-assignment-done

#876 Coffee website+
  public/Day-187/index.html
  public/Day-187/script.js
  public/Day-187/style.css
Labels: SSoC25, Beginner, points-assignment-done

#877 Social Media Dashboard+
  public/Day-188/index.html
  public/Day-188/script.js
  public/Day-188/style.css
Labels: SSoC25, Beginner, points-assignment-done

#879 Ghost Game+
  public/Day-190/display.png
  public/Day-190/favicon.png
  public/Day-190/img/climber.png
  public/Day-190/img/door.png
  public/Day-190/img/ghost-jumping.png
  public/Day-190/img/ghost-standing.png
  public/Day-190/img/tower.png
  public/Day-190/index.html
  public/Day-190/libs/p5.dom.min.js
  public/Day-190/libs/p5.js
  public/Day-190/libs/p5.play.js
  public/Day-190/libs/p5.sound.js
  public/Day-190/sketch.js
  public/Day-190/style.css
Labels: SSoC25, Beginner, points-assignment-done

#881 Monkey Game+
  public/Day-191/display.png
  public/Day-191/favicon.png
  public/Day-191/img/Monkey_01.png
  public/Day-191/img/Monkey_02.png
  public/Day-191/img/Monkey_03.png
  public/Day-191/img/Monkey_04.png
  public/Day-191/img/Monkey_05.png
  public/Day-191/img/Monkey_06.png
  public/Day-191/img/Monkey_07.png
  public/Day-191/img/Monkey_08.png
  public/Day-191/img/Monkey_09.png
  public/Day-191/img/Monkey_10.png
  public/Day-191/img/banana.png
  public/Day-191/img/jungle.jpg
  public/Day-191/img/obstacle.png
  public/Day-191/img/stone.png
  public/Day-191/index.html
  public/Day-191/libs/p5.dom.min.js
  public/Day-191/libs/p5.js
  public/Day-191/libs/p5.play.js
  public/Day-191/libs/p5.sound.min.js
  public/Day-191/sketch.js
  public/Day-191/style.css
Labels: SSoC25, Beginner, points-assignment-done

#883 Pinball Game+
  public/Day-193/index.html
  public/Day-193/script.js
  public/Day-193/style.css
Labels: SSoC25, Beginner, points-assignment-done

#887 Movie UI Update+
  public/MovieSeatBooking/index.html
  public/MovieSeatBooking/script.js
  public/MovieSeatBooking/style.css
Labels: SSoC25, Beginner, points-assignment-done
